-- Linux Security Monitoring
-- PostgreSQL 14+ compatible relational model.
-- Demonstrates process, network, authentication, and persistence telemetry.
-- All sample records are synthetic. No host configuration is modified.

BEGIN;

CREATE SCHEMA IF NOT EXISTS linux_security;
SET search_path TO linux_security, public;

CREATE TABLE IF NOT EXISTS monitored_hosts (
    host_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hostname TEXT NOT NULL UNIQUE,
    environment TEXT NOT NULL
        CHECK (environment IN ('development', 'test', 'staging', 'production')),
    last_seen TIMESTAMPTZ,
    CHECK (hostname <> '')
);

CREATE TABLE IF NOT EXISTS processes (
    process_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES monitored_hosts(host_id) ON DELETE CASCADE,
    pid INTEGER NOT NULL CHECK (pid > 0),
    parent_pid INTEGER CHECK (parent_pid IS NULL OR parent_pid >= 0),
    effective_uid INTEGER NOT NULL CHECK (effective_uid >= 0),
    process_name TEXT NOT NULL,
    executable_path TEXT,
    command_line TEXT,
    effective_capabilities NUMERIC(20, 0) NOT NULL DEFAULT 0
        CHECK (effective_capabilities >= 0),
    observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (host_id, pid, observed_at),
    CHECK (process_name <> '')
);

CREATE INDEX IF NOT EXISTS idx_processes_host_pid_time
    ON processes (host_id, pid, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_processes_executable
    ON processes (executable_path)
    WHERE executable_path IS NOT NULL;

CREATE TABLE IF NOT EXISTS network_connections (
    connection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES monitored_hosts(host_id) ON DELETE CASCADE,
    process_id BIGINT REFERENCES processes(process_id) ON DELETE SET NULL,
    protocol TEXT NOT NULL CHECK (protocol IN ('tcp', 'tcp6', 'udp', 'udp6')),
    connection_state TEXT NOT NULL,
    local_address INET,
    local_port INTEGER NOT NULL CHECK (local_port BETWEEN 0 AND 65535),
    remote_address INET,
    remote_port INTEGER CHECK (remote_port IS NULL OR remote_port BETWEEN 0 AND 65535),
    observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_connections_host_state_time
    ON network_connections (host_id, connection_state, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_connections_local_port
    ON network_connections (local_port, connection_state);

CREATE TABLE IF NOT EXISTS authentication_events (
    auth_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES monitored_hosts(host_id) ON DELETE CASCADE,
    event_time TIMESTAMPTZ NOT NULL,
    username TEXT NOT NULL,
    source_address INET,
    service_name TEXT NOT NULL DEFAULT 'sshd',
    outcome TEXT NOT NULL CHECK (outcome IN ('success', 'failure', 'invalid', 'locked')),
    authentication_method TEXT,
    session_id TEXT,
    CHECK (username <> '')
);

CREATE INDEX IF NOT EXISTS idx_auth_source_time
    ON authentication_events (host_id, source_address, event_time DESC);

CREATE INDEX IF NOT EXISTS idx_auth_user_time
    ON authentication_events (host_id, username, event_time DESC);

CREATE TABLE IF NOT EXISTS persistence_artifacts (
    artifact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES monitored_hosts(host_id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL CHECK (
        artifact_type IN ('systemd-unit', 'cron', 'authorized-key', 'autostart', 'init-script')
    ),
    artifact_path TEXT NOT NULL,
    owner_uid INTEGER NOT NULL CHECK (owner_uid >= 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    world_writable BOOLEAN NOT NULL DEFAULT FALSE,
    content_sha256 TEXT,
    command TEXT,
    observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (host_id, artifact_path, observed_at)
);

CREATE INDEX IF NOT EXISTS idx_persistence_enabled
    ON persistence_artifacts (host_id, artifact_type, observed_at DESC)
    WHERE enabled;

CREATE TABLE IF NOT EXISTS security_findings (
    finding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES monitored_hosts(host_id) ON DELETE CASCADE,
    category TEXT NOT NULL CHECK (
        category IN ('process', 'network', 'authentication', 'persistence')
    ),
    severity TEXT NOT NULL CHECK (
        severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')
    ),
    title TEXT NOT NULL,
    evidence JSONB NOT NULL DEFAULT '{}'::JSONB,
    recommendation TEXT NOT NULL,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    occurrence_count INTEGER NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'investigating', 'resolved', 'false_positive')),
    CHECK (last_seen >= first_seen)
);

CREATE INDEX IF NOT EXISTS idx_findings_open_severity
    ON security_findings (severity, last_seen DESC)
    WHERE status IN ('open', 'investigating');

CREATE INDEX IF NOT EXISTS idx_findings_evidence
    ON security_findings USING GIN (evidence);

-- Seed data is idempotent so the script can be run repeatedly.
INSERT INTO monitored_hosts (hostname, environment, last_seen)
VALUES
    ('linux-web-01', 'production', CURRENT_TIMESTAMP),
    ('linux-db-01', 'production', CURRENT_TIMESTAMP)
ON CONFLICT (hostname) DO UPDATE
SET last_seen = EXCLUDED.last_seen;

INSERT INTO processes (
    host_id, pid, parent_pid, effective_uid, process_name,
    executable_path, command_line, effective_capabilities, observed_at
)
SELECT h.host_id, sample.pid, sample.parent_pid, sample.uid, sample.name,
       sample.executable, sample.command_line, sample.capabilities,
       TIMESTAMPTZ '2026-10-10 06:00:00+00'
FROM monitored_hosts h
CROSS JOIN (
    VALUES
        (401, 1, 0, 'curl', '/tmp/curl',
         'curl https://example.invalid/payload', 0::NUMERIC),
        (512, 1, 0, 'sshd', '/usr/sbin/sshd',
         '/usr/sbin/sshd -D', 0::NUMERIC),
        (720, 1, 0, 'dockerd', '/usr/bin/dockerd',
         '/usr/bin/dockerd', 2097152::NUMERIC)
) AS sample(pid, parent_pid, uid, name, executable, command_line, capabilities)
WHERE h.hostname = 'linux-web-01'
  AND NOT EXISTS (
      SELECT 1 FROM processes p
      WHERE p.host_id = h.host_id
        AND p.pid = sample.pid
        AND p.observed_at = TIMESTAMPTZ '2026-10-10 06:00:00+00'
  );

INSERT INTO network_connections (
    host_id, process_id, protocol, connection_state, local_address,
    local_port, remote_address, remote_port, observed_at
)
SELECT h.host_id,
       p.process_id,
       sample.protocol,
       sample.state,
       sample.local_address::INET,
       sample.local_port,
       NULLIF(sample.remote_address, '')::INET,
       sample.remote_port,
       TIMESTAMPTZ '2026-10-10 06:01:00+00'
FROM monitored_hosts h
CROSS JOIN (
    VALUES
        ('tcp', 'LISTEN', '0.0.0.0', 2375, '', NULL::INTEGER, 720),
        ('tcp', 'LISTEN', '127.0.0.1', 5432, '', NULL::INTEGER, NULL::INTEGER),
        ('tcp', 'LISTEN', '0.0.0.0', 22, '', NULL::INTEGER, 512)
) AS sample(protocol, state, local_address, local_port, remote_address, remote_port, pid)
LEFT JOIN processes p
    ON p.host_id = h.host_id
   AND p.pid = sample.pid
   AND p.observed_at = TIMESTAMPTZ '2026-10-10 06:00:00+00'
WHERE h.hostname = 'linux-web-01'
  AND NOT EXISTS (
      SELECT 1 FROM network_connections c
      WHERE c.host_id = h.host_id
        AND c.local_port = sample.local_port
        AND c.observed_at = TIMESTAMPTZ '2026-10-10 06:01:00+00'
  );

INSERT INTO authentication_events (
    host_id, event_time, username, source_address, service_name,
    outcome, authentication_method
)
SELECT h.host_id,
       TIMESTAMPTZ '2026-10-10 06:10:00+00' + sample.event_offset * INTERVAL '1 second',
       'admin',
       '203.0.113.44'::INET,
       'sshd',
       sample.outcome,
       'password'
FROM monitored_hosts h
CROSS JOIN (
    SELECT generate_series(0, 4) AS event_offset, 'failure'::TEXT AS outcome
    UNION ALL
    SELECT 5, 'success'
) AS sample
WHERE h.hostname = 'linux-web-01'
  AND NOT EXISTS (
      SELECT 1 FROM authentication_events a
      WHERE a.host_id = h.host_id
        AND a.event_time =
            TIMESTAMPTZ '2026-10-10 06:10:00+00'
            + sample.event_offset * INTERVAL '1 second'
        AND a.username = 'admin'
        AND a.source_address = '203.0.113.44'::INET
  );

INSERT INTO persistence_artifacts (
    host_id, artifact_type, artifact_path, owner_uid,
    enabled, world_writable, command, observed_at
)
SELECT h.host_id, sample.kind, sample.path, sample.owner_uid,
       TRUE, sample.world_writable, sample.command,
       TIMESTAMPTZ '2026-10-10 06:15:00+00'
FROM monitored_hosts h
CROSS JOIN (
    VALUES
        ('systemd-unit', '/etc/systemd/system/worker.service',
         0, TRUE, '/tmp/worker'),
        ('cron', '/etc/cron.d/backup',
         0, FALSE, '/usr/local/sbin/backup')
) AS sample(kind, path, owner_uid, world_writable, command)
WHERE h.hostname = 'linux-web-01'
  AND NOT EXISTS (
      SELECT 1 FROM persistence_artifacts a
      WHERE a.host_id = h.host_id
        AND a.artifact_path = sample.path
        AND a.observed_at = TIMESTAMPTZ '2026-10-10 06:15:00+00'
  );

-- Process indicators distinguish evidence from a definitive compromise verdict.
INSERT INTO security_findings (
    host_id, category, severity, title, evidence, recommendation
)
SELECT h.host_id,
       'process',
       'HIGH',
       'Executable resides in a temporary directory',
       jsonb_build_object(
           'pid', p.pid,
           'name', p.process_name,
           'path', p.executable_path
       ),
       'Validate executable provenance, file hash, permissions, and process ancestry.'
FROM monitored_hosts h
JOIN processes p ON p.host_id = h.host_id
WHERE h.hostname = 'linux-web-01'
  AND (p.executable_path LIKE '/tmp/%'
       OR p.executable_path LIKE '/dev/shm/%')
  AND NOT EXISTS (
      SELECT 1 FROM security_findings f
      WHERE f.host_id = h.host_id
        AND f.category = 'process'
        AND f.title = 'Executable resides in a temporary directory'
        AND f.evidence->>'pid' = p.pid::TEXT
  );

-- A listener on a sensitive port deserves review; reachability depends on
-- routing, firewall rules, namespaces, and the actual bind address.
INSERT INTO security_findings (
    host_id, category, severity, title, evidence, recommendation
)
SELECT h.host_id,
       'network',
       CASE
           WHEN c.local_port = 2375 THEN 'HIGH'
           WHEN c.local_port IN (3306, 5432, 6379, 27017) THEN 'MEDIUM'
           WHEN c.local_address = '0.0.0.0'::INET
             OR c.local_address = '::'::INET THEN 'MEDIUM'
           ELSE 'LOW'
       END,
       CASE
           WHEN c.local_port = 2375 THEN 'Docker API listener requires exposure review'
           WHEN c.local_port IN (3306, 5432, 6379, 27017)
               THEN 'Database or cache listener requires network review'
           ELSE 'Listener requires exposure review'
       END,
       jsonb_build_object(
           'protocol', c.protocol,
           'address', c.local_address::TEXT,
           'port', c.local_port,
           'pid', p.pid,
           'process', p.process_name
       ),
       'Confirm listener ownership, firewall policy, authentication, and intended reachability.'
FROM monitored_hosts h
JOIN network_connections c ON c.host_id = h.host_id
LEFT JOIN processes p ON p.process_id = c.process_id
WHERE h.hostname = 'linux-web-01'
  AND c.connection_state = 'LISTEN'
  AND (
      c.local_port IN (2375, 3306, 5432, 6379, 27017)
      OR c.local_address = '0.0.0.0'::INET
      OR c.local_address = '::'::INET
  )
  AND NOT EXISTS (
      SELECT 1 FROM security_findings f
      WHERE f.host_id = h.host_id
        AND f.category = 'network'
        AND f.evidence->>'port' = c.local_port::TEXT
  );

-- Detect repeated authentication failures by source in a rolling time window.
WITH source_failures AS (
    SELECT host_id, source_address, COUNT(*) AS failure_count,
           MIN(event_time) AS first_failure,
           MAX(event_time) AS last_failure
    FROM authentication_events
    WHERE outcome IN ('failure', 'invalid')
      AND event_time >= CURRENT_TIMESTAMP - INTERVAL '1 day'
    GROUP BY host_id, source_address
    HAVING COUNT(*) >= 5
)
INSERT INTO security_findings (
    host_id, category, severity, title, evidence, recommendation,
    first_seen, last_seen, occurrence_count
)
SELECT sf.host_id,
       'authentication',
       CASE WHEN sf.failure_count >= 10 THEN 'HIGH' ELSE 'MEDIUM' END,
       'Repeated authentication failures from one source',
       jsonb_build_object(
           'source_address', sf.source_address::TEXT,
           'failure_count', sf.failure_count,
           'first_failure', sf.first_failure,
           'last_failure', sf.last_failure
       ),
       'Correlate with identity and network logs before applying an access restriction.',
       sf.first_failure, sf.last_failure, sf.failure_count::INTEGER
FROM source_failures sf
WHERE NOT EXISTS (
    SELECT 1 FROM security_findings f
    WHERE f.host_id = sf.host_id
      AND f.category = 'authentication'
      AND f.title = 'Repeated authentication failures from one source'
      AND f.evidence->>'source_address' = sf.source_address::TEXT
);

-- A successful event following multiple failures is a correlation signal.
WITH ordered_auth AS (
    SELECT a.*,
           COUNT(*) FILTER (WHERE outcome IN ('failure', 'invalid'))
           OVER (
               PARTITION BY host_id, source_address
               ORDER BY event_time
               RANGE BETWEEN INTERVAL '15 minutes' PRECEDING AND CURRENT ROW
           ) AS failures_in_window
    FROM authentication_events a
)
SELECT h.hostname,
       a.event_time,
       a.username,
       a.source_address,
       a.outcome,
       a.failures_in_window
FROM ordered_auth a
JOIN monitored_hosts h ON h.host_id = a.host_id
WHERE a.outcome = 'success'
  AND a.failures_in_window >= 5
ORDER BY a.event_time DESC;

-- Find enabled persistence artifacts with excessive write permissions or
-- paths that merit investigation. These indicators require contextual review.
SELECT h.hostname,
       a.artifact_type,
       a.artifact_path,
       a.owner_uid,
       a.world_writable,
       a.command,
       CASE
           WHEN a.world_writable THEN 'HIGH'
           WHEN a.artifact_path LIKE '/tmp/%'
             OR a.artifact_path LIKE '/dev/shm/%' THEN 'MEDIUM'
           ELSE 'LOW'
       END AS review_priority
FROM persistence_artifacts a
JOIN monitored_hosts h ON h.host_id = a.host_id
WHERE a.enabled
  AND (
      a.world_writable
      OR a.artifact_path LIKE '/tmp/%'
      OR a.artifact_path LIKE '/dev/shm/%'
  )
ORDER BY review_priority DESC, a.artifact_path;

-- Current unresolved findings are the operational triage view.
CREATE OR REPLACE VIEW unresolved_findings AS
SELECT f.finding_id,
       h.hostname,
       f.category,
       f.severity,
       f.title,
       f.evidence,
       f.recommendation,
       f.first_seen,
       f.last_seen,
       f.occurrence_count,
       f.status
FROM security_findings f
JOIN monitored_hosts h ON h.host_id = f.host_id
WHERE f.status IN ('open', 'investigating');

SELECT hostname, category, severity, title, evidence, recommendation
FROM unresolved_findings
ORDER BY
    CASE severity
        WHEN 'CRITICAL' THEN 5
        WHEN 'HIGH' THEN 4
        WHEN 'MEDIUM' THEN 3
        WHEN 'LOW' THEN 2
        ELSE 1
    END DESC,
    last_seen DESC;

-- Transactional integrity: all schema and demonstration data are committed together.
COMMIT;
